# Generated by Django 3.1.3 on 2020-11-11 11:09

from django.db import migrations
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20201108_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=private_files.models.fields.PrivateFileField(upload_to=''),
        ),
    ]
