# Generated by Django 3.1.3 on 2020-11-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0002_auto_20201108_1524'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('C', 'Chose gift'), ('T', 'Transferred')], max_length=1)),
                ('timestamp_ts', models.DateTimeField(auto_now_add=True)),
                ('by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acting_users', to=settings.AUTH_USER_MODEL)),
                ('from_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_users', to=settings.AUTH_USER_MODEL)),
                ('gift_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifts.gift')),
                ('to_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
