# Generated by Django 3.1.3 on 2020-11-11 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import private_files.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phase', models.CharField(choices=[('P', 'Pre Start'), ('N', 'Normal Raffle'), ('G', 'Gift Swap'), ('F', 'Finished')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_ts', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(max_length=120)),
                ('wrapped', models.BooleanField(default=True)),
                ('image', private_files.models.fields.PrivateFileField(upload_to='')),
                ('pixelated_image', models.ImageField(editable=False, upload_to='')),
                ('added_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.RESTRICT, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.raffleevent')),
                ('given_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prizes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_ts', models.DateTimeField(auto_now_add=True)),
                ('action_type', models.CharField(choices=[('C', 'Chose gift'), ('T', 'Transferred')], max_length=1)),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acting_users', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.raffleevent')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_users', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.gift')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
