# Generated by Django 3.1.3 on 2020-11-11 13:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_auto_20201111_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.raffleevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='raffleparticipation',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='event_user_uq'),
        ),
    ]
