# Generated by Django 3.1.3 on 2020-11-29 15:16

import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20201121_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='container_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gift',
            name='image',
            field=models.ImageField(storage=custom_storages.MediaStorage, upload_to=''),
        ),
    ]
