# Generated by Django 3.1.3 on 2020-11-29 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20201129_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='add_ts',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
